### ISSUE TITLE
AES128 CBC mode performance compared with openssl

### ISSUE THREAD

**Issue by keepsimple1** [RustCrypto/block-ciphers#133]
Is there any performance measurements of AES128 (CBC) against other common packages, e.g. [`openssl`](https://crates.io/crates/openssl) ?

I've done a simple non-scientific performance measurement compared with `openssl`, and the result showing it's about 7x slower than `openssl`.  I was surprised and wanted to check what others have seen. 

my test: (AES128 CBC)
step 1.  generates a random string of 50 chars (using `rand` crate).
step 2.  encrypt the plain string.
step 3.  decrypt the encrypted.
step 4.  assert the result is same as the plain string.

Repeat step 1-4 for 100 times.

`block-ciphers`:  58ms total,  `openssl` 8ms total.

**Comment by newpavlov** [comment]
Try to use `RUSTFLAGS="-C target-feature=+aes"` (RUSTFLAGS="-C target-feature=+aes,+ssse3" if you want to measure CTR performance). At the moment `aes` crate supports switching between hardware accelerated `aesni` implementation and the bitsliced one from `aes-soft` only at compilation time, while IIUC  OpenSSL does detection of hardware capabilities at runtime. So quite probably you measure a difference between software and hardware based implementations.

**Comment by keepsimple1** [comment]
Just add a note that I ran the same test on Raspberry Pi 3, where AFAIK there is no hardware acceleration for AES.  The result is similar: 

openssl:  80ms
RustCrypto: 590ms

Again my test is only one particular case, but I think it will be good (and worth it) for this project to have a benchmark comparing with `openssl`. Just my 2 cents.

**Comment by tarcieri** [comment]
The `aes-soft` crate's performance isn't as good as it could be. It uses techniques for constant-time operation which have not yet been optimized.

**Comment by tarcieri** [comment]
Since this is about `aes-soft`, I'd consider it a dup of #65
