### ISSUE TITLE
verify request for ownership of "cipher" crate

### ISSUE THREAD

**Issue by o-klp** [RustCrypto/block-ciphers#156]
@newpavlov reached out to me and requested I transfer ownership of the cipher crate. I'd be happy to do so. Before transferring, I wanted to confirm the request came from the github user.

@newpavlov can you confirm?

**Comment by o-klp** [comment]
Thanks @newpavlov ! I've added you as an owner:

```
$ cargo owner --add newpavlov cipher
    Updating crates.io index
       Owner user newpavlov has been invited to be an owner of crate cipher
```

Once you accept, feel free to remove myself as an owner and publish over the package. It was a small pet project I threw up on a whim (probably should have used a different name. Ah well)

**Comment by newpavlov** [comment]
Thank you!
