### ISSUE TITLE
aes: reduce ParBlocks from 8 to 4 in next breaking release?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/block-ciphers#181]
8 was ostensibly chosen because this used to be the optimal number of AES-NI blocks to compute in parallel. From Shay Gueron's RWC 2013 talk [[1]]:

<img width="400" alt="Screen Shot 2020-10-27 at 9 12 24 AM" src="https://user-images.githubusercontent.com/797/97329721-99a49c00-1834-11eb-8cc6-324b435f17d4.png">

However on newer Intel architectures, equivalent performance can be had with 4 blocks [[2]], and the forthcoming vectorized AES-NI instructions ("VAES") will leverage AVX512 and operate on 4 AES blocks as well (4 x 128-bit = 512-bit) [[3]].

4 blocks is also the optimal number for a 64-bit fixsicing implementation (#180). For a 32-bit implementation, it's twice as many blocks as are necessary, but we can just double the 2-block implementation. Alternatively we could look at using `ParBlocks = 2` on 32-bit architectures.

Should we reduce the number of parallel blocks to 4? It seems like it most closely aligns with various implementations. Would it make sense to make it smaller on 32-bit architectures, or would that be too much of a pain?

[1]: https://crypto.stanford.edu/RealWorldCrypto/slides/gueron.pdf
[2]: https://github.com/openssl/openssl/blob/master/crypto/aes/asm/aesni-x86_64.pl
[3]: https://eprint.iacr.org/2018/392.pdf

**Comment by newpavlov** [comment]
Ideally number of blocks should be chosen based on CPU-family. IIRC on older Intel CPUs optimal number of blocks varied from 4 to 6, but `#[cfg(target_cpu = "...")]` does not currently work, so we would have to rely on runtime detection, which  is... not great. If my measurements correct, on Ryzen 2700X `ParBlocks=4` significantly reduces performance (~30-40%), so I think such change should be done only after careful benchmarking.

**Comment by tarcieri** [comment]
Will leave this at 8 rounds for now. Please leave a comment if you'd like this issue reopened/revisited.
