### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by segfauIt** [RustCrypto/block-ciphers#19]
Please add some examples. For example, I need to know how to encrypt/decrypt a variable using the blowfish cipher. Thanks!

**Comment by newpavlov** [comment]
Sorry for the late reply!

Currently I can't work on improving documentation right now, but I hope I'll be able to on the next weekend. Can you share more information about your use-case? I assume you want to use blowfish with block mode? In that case take a look at [`block-modes`](https://crates.io/crates/block-modes) crate, currently it's being re-worked, but v0.1.0 should be usable. Small (unckecked) example:

```Rust
use block_modes::{BlockMode, BlockModeIv, Cbc};
use block_modes::block_padding::Iso7816;
use blowfish::Blowfish;

type MyCipher = BlockMode<Blowfish, Iso7816>;

let mut cipher = MyCipher::new_varkey(key, iv).unwrap();
// buffer must have enough space for message+padding
let mut buffer = [0u8; 32];
buffer[..msg_len].copy_from_slice(msg);
let encrypted_msg = cipher.encrypt_pad(&mut buffer, msg_len).unwrap();

let mut cipher = MyCipher::new_varkey(key, iv).unwrap();
let decrypted_msg = cipher.decrypt_pad(encrypted_data).unwrap();
```

**Comment by newpavlov** [comment]
I've added an example to the readme. I think it will be a good starting point. Feel free to open additional issues/PRs if you'll have ideas on how to improve docs!

**Comment by edsky** [comment]
Cannot use the demo above

**Comment by newpavlov** [comment]
@edsky 
The example is fixed now.
