### ISSUE TITLE
block-modes: `std` feature enabled by default?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/block-ciphers#228]
This might be moot soon, but I thought it was a little strange:

https://github.com/RustCrypto/block-ciphers/blob/master/block-modes/Cargo.toml#L22

**Comment by newpavlov** [comment]
Since it's quite probable that this crate will be used directly (compared to the block cipher or trait crates), I have intentionally enabled `std` by default, similarly to how we do it for example for hashes. Do you think we should not do it?

**Comment by tarcieri** [comment]
Oh, okay.

I guess I'm a little torn and not entirely clear when it's a good idea to enable `std` or not, but I suppose the closer it is to end-user facing, the more defensible it is to enable it by-default.

**Comment by newpavlov** [comment]
Yeah, I am also not 100% sure about having it by default. I guess it depends on how often in practice users use `encrypt_vec`/`decrypt_vec` and implementation of the `Error` trait on error types.
