### ISSUE TITLE
Too much undefined behavior

### ISSUE THREAD

**Issue by gnzlbg** [RustCrypto/block-ciphers#23]
I started to write a PR to just show how using `#[target_feature]` would look like but I encountered too much undefined behavior in the process (fixing it was taking more time than actually dealing with target feature). 

I've only taken a look at a tiny fraction of the `aesni` crate, but it seems that references to uninitialized memory are created pretty much everywhere (all references must point to initialized memory [0]): 
    * https://github.com/RustCrypto/block-ciphers/blob/master/aes/aesni/src/aes128/expand.rs#L21
    * https://github.com/RustCrypto/block-ciphers/blob/master/aes/aesni/src/aes128/expand.rs#L36

The way I fixed these was by using `ptr::write` to write to uninitialized memory without creating a reference. 

There are also reads memory out-of-bounds: https://github.com/RustCrypto/block-ciphers/blob/master/aes/aesni/src/aes192/expand.rs#L51

The way I fixed this was by creating a stack buffer of appropriate size in the `mod.rs` file which I initialized with `mem::uninitialized`, and then using `ptr::write` to write the `GenericArray` into the head of the buffer, so that the vector load never reads memory out of bounds - the memory read is only partially initialized though, and reading vector lanes with uninitialized memory should be done with care (so that no UB is introduced). 

---

[0] `&T as *const T` and `&mut T as *mut T` might not end up being undefined behavior because they _might_ end up being atomic operations in the memory model that create a raw pointer directly without creating a reference (so that no reference to uninitialized memory is ever created by these expressions, preventing them from invoking undefined behavior).

**Comment by newpavlov** [comment]
This uninitialized memory is stack allocated, we always fully fill it and never read uninitialized values from it. I don't see how it can cause UB. Essentially we just ask compiler reserve N bytes on stack for us to fill. Also I don't quite get why you think that `_mm_loadu_si128(key.as_ptr() as *const __m128i)` is UB. As I see it it's the most basic way to load data into `__m128i` (essentially `xmm` register). Can you be more explicit with your arguments?

As for out-of-bound read [Intel AES-NI white-paper](https://software.intel.com/sites/default/files/article/165683/aes-wp-2012-09-22-v01.pdf) (p. 32) uses almost exactly the same code, and I don't see how it can cause problems in practice.

As for migration to `#[target_feature]` I would be grateful if you discuss proposed changes first.

**Comment by gnzlbg** [comment]
> This uninitialized memory is stack allocated, we always fully fill it and never read uninitialized values from it. I don't see how it can cause UB.

As mentioned, the undefined behavior in the library is not of type "read of uninitialized memory", but "reference to uninitialized memory". This code never reads uninitialized memory:

```rust
let x: i32 = mem::uninitialized;
let y = &x; // UB
```

yet it has undefined behavior because it creates a reference to memory that is uninitialized (references always point to initialized memory). 

In your code, when you write `x[i] = 2;` that's creating a reference `&mut` to the uninitialized memory `i`, which is undefined behavior, and then using that reference to write `2` to that memory. 

What you probably want to do here is:

```rust
ptr::write(x.as_mut_ptr().offset(i), 2);
```

which creates a raw pointer, instead of a reference, and writes to it using `ptr::write`. 

> Also I don't quite get why you think that _mm_loadu_si128(key.as_ptr() as *const __m128i) is UB. 

You are using `_mm_loadu_si128` twice, to read 256bit of data (32 bytes), from an `[u8; 24]` (a 24 byte long array. You read the first 128-bits (16 bytes) of the array using the first `_mm_loadu_si128`, which is ok. Then, you offset the pointer by 16 bytes, to read another 16 bytes using the second `_mm_loadu_si128`. However, only 24 - 16 = 8 bytes are in the array, which means that you read 8 bytes out-of-bounds. That's undefined behavior.

**Comment by gnzlbg** [comment]
FYI the `mem::uninitialized` docs actually list the only safe ways of initializing uninitialized memory: https://doc.rust-lang.org/std/mem/fn.uninitialized.html#undefined-behavior

**Comment by newpavlov** [comment]
>In the code, x[i] = 2; creates a reference &mut to the uninitialized memory at x.as_ptr().offset(i), which is undefined behavior, and then uses that reference to write 2 to that memory.

It's a bit pedantic to my taste, as both of those variants are strictly equivalent to me when we work with plain bytes. But, ok, I'll change it, though it will make code a bit noisier.

>FYI the mem::uninitialized docs list the only safe ways of initializing uninitialized memory: 

Note, that your link talks about types which implement `Drop` I don't see how plain bytes can cause issues here.

>However, only 24 - 16 = 8 bytes are in the array, which means that the program read 8 bytes out-of-bounds. That's undefined behavior.

I know about it. Intel code examples does absolutely the same. I don't see how it can cause problems in practice. But if we are being pedantic, we can change it, luckily this part of the code can tolerate one or two redundant instructions.

**Comment by newpavlov** [comment]
I'll write a PR with the discussed changes. Do you have any other places which you think cause UB?

**Comment by gnzlbg** [comment]
> I know about it. Intel code example does absolutely the same. 

Then Intel code example has undefined behavior as well.

> But if we are being pedantic, we can change it, luckily this part of the code can tolerate one or two redundant instructions.

I think it can be changed without redundant instructions if you do something like this (I haven't fully checked this code though):

```rust
let key: GenericArray<u8, 24>;
let mut x: [u8; 32] = mem::uninitialized();
ptr::write(x.as_mut_ptr() as *mut GenericArray<u8, 24>, key);
encrypt(x.as_ptr());
// note that we can't pass x by & because that would 
// create a reference to uninitialized memory :( 

fn encrypt(key: *const [u8; 32]) {
    let u : __m128i = _mm_loadu_si128((key as *const u8).offset(16) as *const __m128i);
    // ^^^ the last 8 bytes of u are uninitialized 
    // as long as we overwrite them before we use them everything should be ok
    // but in the mean time one cannot create references to u :(
}
```

> though it will make code a bit noisier.

It makes the code a lot noisier sadly, I have no good ideas about how to make it less noisy here :/ Maybe just use raw pointers instead? Or use `mem::zeroed` instead of mem::uninitialized.. but that might add overhead, I don't know.

> Note, that your link talks only about types which implement Drop, which is obviously not the case here. 

None of the `Drop` stuff applies here (if you are interested, it applies only to drop types, and then you also have to be careful when using the `ptr::read/write` methods because they do not drop values, so you can end up with double drops). 

> It's a bit pedantic to my taste,

For my taste too, but undefined behavior is undefined. 

I'd like to think that the Rust from the future might use this to optimize in some cases. Those cases are not the one in this crate, but if the behavior is undefined other programs might behave incorrectly as a consequence of the optimization. So Rust from the future decides to `assert!` on debug builds if this undefined behavior is triggered, which is fine, since Rust is allowed to generate any code if you invoke undefined behavior, and an `assert!` alerting you is one of the nicest things it can do. 

So even though your program doesn't benefit from the optimization, because of the UB, it might some day panic.

I don't know if that motivates you to fix these, but that's what I tell myself to motivate myself.

---

FWIW the root issue here is that the code uses `mem::uninitialized`, which is extremely easy to use incorrectly. 

Before you start fixing these, I'd recommend you to read on these issues, and play with `unions`. An union makes uninitialized memory much nicer to use, and much harder to use incorrectly.

**Comment by newpavlov** [comment]
>Before you start fixing these, I'd recommend you to read on these issues, and play with unions. An union makes uninitialized memory much nicer to use, and much harder to use incorrectly.

Can you show how `MaybeUninit` union can be used here? Create `uninit` variant, then pointer to it, do writing and convert to an array variant? IIUC it does not bring much to the table here and even worse will make code even noisier.

**Comment by gnzlbg** [comment]
> Can you show how MaybeUninit union can be used here?

Not really, I've never used `MaybeUninit` myself. I just read the RFC a couple of days ago. 

What I currently always do in `std::arch` and `std::simd` is:

```rust
union U {
    x: i32,
    y: (), // uninitialized variant
}
// create uninitialized value:
let u = U { y: () };
// initialize it to some value:
let value = 42_i32;  
ptr::write(&mut u  /* always ok: u is initialized */ as *mut i32, value);
```

What you want here is to have an array that contains partially initialized values, so I would do:

```rust
union U {
    x: u8,
    y: (), // uninitialized variant
}
let array: [U; 32] = [U { y: () }; 32]; // uninitialized values
// note: array itself is initialized, and so are the elements of it
ptr::write(&mut array[3] /* ok: the element is initialized */ as *mut u8, some_value);
```

Does that make sense?

**Comment by newpavlov** [comment]
While I see the motivation behind making creation of uninitialized data safe and moving unsafety to final conversion from union to "plain" type, currently I think that for small cases like this where you essentially deal with one unsafe `block` in which you handle everything, union based code makes code less readable, and thus less reviewable. But I guess, it's a matter of preference.

>I think it can be changed without redundant instructions if you do something like this (I haven't fully checked this code though):

I've checked you code on godbolt, and surprisingly it has [produced](https://godbolt.org/g/LJp6Px) a good result. (`movups` got replaced with `movsd`)

**Comment by gnzlbg** [comment]
> I've checked your approach on godbolt, and surprisingly it has produced a good result. (movups got replaced with movsd)

Yeah, you should really check the code generation for all these changes. You don't want to inadvertently produce a regression.

> union based code makes code less readable, and thus less reviewable. But I guess, it's a matter of preference and habits.

FWIW, I started with that opinion, and it took me about 2 weeks to change it because I started discovering more and more undefined behavior due to `uninitialized` in my programs. I guess that at some point, I might even like `MaybeUninit<T>`. 

For example, for the array indexing case (`x[i]`), when is undefined behavior introduced? I wrote above that creating a reference to an element of the array was UB, because the element is uninitialized, but actually UB is introduced in the program well before that. There is an implementation of `IndexMut` for arrays somewhere, where the `index_mut(&mut self, usize)` takes a `&mut self`. That `&mut self` right there is already UB because the array itself is `uninitialized`, and we haven't even started indexing anything yet. 

I started to like the `union` approach (and `MaybeUninit` is just an union with convenience methods)  because it makes invoking UB in subtle ways like via `&self` much harder to trigger. 

If you want to keep the `x[i]` syntax, you could add an `index_assign!(array, index, value)` that abstracts the boilerplate away and is safe.

**Comment by gnzlbg** [comment]
Nice, this was really quick!
