### ISSUE TITLE
fixslice64.rs got clobbered?

### ISSUE THREAD

**Issue by peterdettman** [RustCrypto/block-ciphers#246]
aes/src/soft/fixslice64.rs appears to have been copied over with the contents of aes/src/soft/fixslice32.rs in commit https://github.com/RustCrypto/block-ciphers/commit/61cd5de91ba2cccd698e6a75d14eaa344d83cd0b.

**Comment by tarcieri** [comment]
Oh wow, that's bad.

Would you like to take care of fixing it or should I?

**Comment by peterdettman** [comment]
Please take care of it; I'd need to refresh my setup.
