### ISSUE TITLE
aes: expose round function

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/block-ciphers#252]
Exposing the AES round function is of course another level of cryptographic kryptonite beyond the raw block function, but we do have a valid use case.

Deoxys would benefit: https://github.com/RustCrypto/AEADs/pull/311

I think it's possible to build an abstraction for it over the various backends we have.

**Comment by zer0x64** [comment]
A quick note here that it would also be pretty useful if we want to implement AEGIS one day
