### ISSUE TITLE
Endianess of Blowfish

### ISSUE THREAD

**Issue by Veykril** [RustCrypto/block-ciphers#26]
Is there a reason for Blowfish using big-endian transformation for the integer part or would it be possible to implement a maybe? generic version of the Blowfish struct that would allow you to uses LittleEndian or BigEndian at the users will? Cause for my project I require it reading them in LittleEndian for the en/decryption to be valid.

**Comment by newpavlov** [comment]
Sorry for the late reply! Implementation was mostly inherited from `rust-crypto`, and IIRC reference implementations also use big-endian order. I guess we can add `BlowfishBE` and `BlowfishLE` ciphers without any problems.

**Comment by fzzr-** [comment]
@Veykril Are you mean ["Blowfish-compat"](https://stackoverflow.com/a/11423057/829264) support?

**Comment by Veykril** [comment]
I believe that's what i mean indeed. never heard of that specific term before but it looks like that's what i was looking for.

**Comment by fzzr-** [comment]
@Veykril Check this out: 
https://github.com/fzzr-/blowfish-compat.rs

**Comment by Veykril** [comment]
Thanks for that, but I don't need it anymore though since i changed the crate for myself back then. Forgot to make a PR out of that.
