### ISSUE TITLE
[Question/Suggestion] AES encryption examples with text

### ISSUE THREAD

**Issue by sciguyryan** [RustCrypto/block-ciphers#277]
Hi there.

It seems I am writing a lot of these today, sorry about that.

I am pretty new to using cryptographic functions, unless one exists would it be possible for an example to be added to the online docs to give an example of a round-trip encryption/decryption with text using the various block ciphers?

The one I am looking at is AES though this would be the case with most of them, I'm finding the docs difficult to follow. The example (here: https://docs.rs/aes/0.7.4/aes/) has actually confused me more than it has helped.

This is what I get for looking at a new language and new subject material at the same time.

Thanks.

**Comment by tarcieri** [comment]
Hi there!

It looks like you've pointed out an important deficiency in the documentation. In the README.md, we try to call out the `aes` crate as something unsuitable for beginners or people looking for a high-level interface:

https://github.com/RustCrypto/block-ciphers/tree/master/aes#%EF%B8%8F-warning-hazmat

However, no such warning exists in the rustdoc, and that's a problem.

Can you look at the documentation in the README.md and see if it leads you where you need to go? If so, we can copy that paragraph into the rustdoc (and ideally, eventually unify the two down the road using new rustdoc features)

**Comment by sciguyryan** [comment]
> 
> 
> Hi there!
> 
> It looks like you've pointed out an important deficiency in the documentation. In the README.md, we try to call out the `aes` crate as something unsuitable for beginners or people looking for a high-level interface:
> 
> https://github.com/RustCrypto/block-ciphers/tree/master/aes#%EF%B8%8F-warning-hazmat
> 
> However, no such warning exists in the rustdoc, and that's a problem.
> 
> Can you look at the documentation in the README.md and see if it leads you where you need to go? If so, we can copy that paragraph into the rustdoc (and ideally, eventually unify the two down the road using new rustdoc features)

Thanks, I will take a look at that later and let you know. I appreciate you pointing me in the right direction!

**Comment by sciguyryan** [comment]
Hi tarcieri.

Apologies for not getting back to you more quickly here. I've been bogged down with university work.

I was able to find the information located via the above page. Copying that into the README file would therefore resolve my issue here.

Thanks again for helping me with this, and for working to produce these crates. I'll leave this open in case you intend on closing with a commit to the effect of the above.
