### ISSUE TITLE
Mentioning the audit from NCC Group

### ISSUE THREAD

**Issue by BlackMagicCoding** [RustCrypto/block-ciphers#292]
Hi,

I am currently searching for a stable, well maintained and if possible even audited crate for using AES in Rust.
At first I was confused when I read on the main page (block-ciphers) that no audit has been performed for crates in this repository... but when you open block-ciphers/aes, you see that there was an audit done by [NCC Group](https://research.nccgroup.com/2020/02/26/public-report-rustcrypto-aes-gcm-and-chacha20poly1305-implementation-review/).
If this is just some outdated line on the main page, you might want to consider updating and mentioning it for the algorithms which have been audited, to avoid potential confusion by users.

Kind regards

**Comment by tarcieri** [comment]
It is an outdated comment. Thanks for pointing it out
