### ISSUE TITLE
Runtime BlockSize

### ISSUE THREAD

**Issue by burdges** [RustCrypto/block-ciphers#3]
There are "wide" block ciphers with a run time configurable block size like AEZ, Lioness, and DJB's upcoming HHFHFH, so `BlockCipher::BlockSize` should probably be replaced with an associated type, so that it can be configured at either compile time or run time according to the cipher.

**Comment by newpavlov** [comment]
In case of configuration at compile time, cipher trait implementation can be generic over `BlockSize` in the same way as some hashes currently generic over `OutputSize`. Run time case a bit harder and I think we will need to use a separate trait for it. (though [alloca support](https://github.com/rust-lang/rfcs/pull/1808) could change it)

**Comment by newpavlov** [comment]
I will close this issue for now. But it could be reopened after implementation of algorithms mentioned by you and if need for runtime dependent block sizes will arise. Until we will come up with a trait which will fit to this use case, ciphers could use trait-less `impl` to provide methods.
