### ISSUE TITLE
Update crates to block-cipher-trait v0.6

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/block-ciphers#32]
Currently only AES crates have been updated.

 Probably RustCrypto/traits#25 should be finished first.

**Comment by dignifiedquire** [comment]
I am having some trouble due to some ciphers being updated and others not, any update on this?

**Comment by Veykril** [comment]
Can we solve this issue in the near future? It makes some crates unuseable if using the newest `block-modes` crate due to dependency version mismatch. I wouldnt mind doing it but i do not know how to generate the needed test data for blobby

**Comment by newpavlov** [comment]
Sorry for the delay! I plan to publish updates today. (see linked PR)
