### ISSUE TITLE
Missing feature flag

### ISSUE THREAD

**Issue by ShaneMurphy2** [RustCrypto/block-ciphers#330]
The crate `aes` has code conditionally disabled behind the feature `aes_armv8`, but that feature was removed from Cargo.toml [here](https://github.com/RustCrypto/block-ciphers/pull/284/commits/bf53411848d764748e39defb5fc0584360d9c42f#diff-fc5bfcfaef34d32bd387f520b95054a6d2af5f6fd776ed6f67dd549721af323fL31). Furthermore, the crate `aes_gcm`, also maintained by RustCrypto though not part of this repository, does not expose a feature to pass though to its dependency on `aes`. In addition, the documentation for `aes` still [refer](https://docs.rs/aes/0.8.1/aes/index.html#armv8-intrinsics-nightly-only) to this feature, so either way I'm a bit lost.

I'm trying to build `aes_gcm` using the armv8 crypto extensions, but for the reasons mentioned I don't see how. 

Apologies if I'm missing something obvious, thanks!

**Comment by newpavlov** [comment]
The ARM backend is now enabled using configuration flags as described [here](https://docs.rs/aes/0.8.1/aes/index.html#configuration-flags). It seems we forgot to remove mention of removed features in the rest of docs.

**Comment by ShaneMurphy2** [comment]
Ah, I didn't scroll to the bottom before diving down the feature flag dependency chain. Is the reason for using a configuration option over a feature flags so that there doesn't need to be a chain of feature flags all the way to the `aes` crate?

**Comment by newpavlov** [comment]
See https://github.com/RustCrypto/block-ciphers/issues/245 for discussion which led to the change.

**Comment by ShaneMurphy2** [comment]
Interesting discussion, all good now. Thanks!
