### ISSUE TITLE
Add Rijndael (not AES)

### ISSUE THREAD

**Issue by sorairolake** [RustCrypto/block-ciphers#341]
Rijndael supports more key sizes (128, 160, 192, 224 and 256 bits are supported) and block sizes (same as key size) than AES.
I think Rijndael is rarely needed, but some software supports it.

**Comment by tarcieri** [comment]
FYI, there's some past discussion about Rijndael here: https://github.com/RustCrypto/block-ciphers/issues/1#issuecomment-814908669

**Comment by newpavlov** [comment]
I am going to close it in favor of #1 (Rijndael is already in the list).
