### ISSUE TITLE
Why use 42u8?

### ISSUE THREAD

**Issue by oilel** [RustCrypto/block-ciphers#347]
[The example](https://docs.rs/aes/latest/aes/#examples) contains 
> let mut block = GenericArray::from([42u8; 16]);

Why use 42u8?

**Comment by newpavlov** [comment]
Because... why not? We need a concrete value for examples and `[42; 16]` is as good as any, while being a well-known reference.

**Comment by tarcieri** [comment]
For posterity: https://en.wikipedia.org/wiki/42_(number)#Popular_culture

**Comment by oilel** [comment]
> Because... why not? We need a concrete value for examples and `[42; 16]` is as good as any, while being a well-known reference.

The 42u8 seems the UTF8 code of symbol *

**Comment by oilel** [comment]
> Because... why not? We need a concrete value for examples and `[42; 16]` is as good as any, while being a well-known reference.

The 42u8 seems the UTF8 code of symbol *
