### ISSUE TITLE
`encrypt_block` vs `encrypt_blocks`, what is 'parallel block processing'?

### ISSUE THREAD

**Issue by KaneGreen** [RustCrypto/block-ciphers#351]
I am recently learning how to use `aes`. I'm reading the [docs](https://docs.rs/aes/0.8.2/aes/).  
Now I note `encrypt_block` can process a single block, while `encrypt_blocks` can process many blocks.  
In the docs' example, there is a comment:
> implementation supports parallel block processing
> number of blocks processed in parallel depends in general on hardware capabilities

I'm wondering, is this *parallel* an automatic multi-thread implement? And the `hardware capabilities` is the CPU core number?

**Comment by tarcieri** [comment]
It leverages [instruction-level parallelism](https://en.wikipedia.org/wiki/Instruction-level_parallelism), which allows a single CPU to compute multiple AES blocks in parallel.

It does not require multiple CPU cores.

**Comment by KaneGreen** [comment]
Thank you.

However, I have an advice: maybe it will be better if some sentences like "this is not by multi-threading" can be added in the docs' comment mentioned above.  
Because I think when users see "parallel", they are more likely to first think of multi-threaded parallelism.

-----------
Besides, I have two more question:
* I have run `cargo bench` on several X86 computers. It seems when AES-NI is disabled, there was always nearly 4x speed-up for `encrypt_blocks`, but just a little speed-up when AES-NI is available. So, does this "parallelism" mainly come from bit-slicing?
* Will I still benefit from the nearly 4x speed-up when I use high-level APIs such as `cbc::Encryptor<aes::Aes128>` and `aes_gcm::Aes256Gcm` if AES-NI is disabled?

**Comment by tarcieri** [comment]
The parallelism comes from the CPU working on multiple blocks in parallel. You should see a roughly 8X speedup versus a single block.

It should be roughly an order of magnitude faster than the bitsliced implementation. That said, the bitsliced implementation computes 4 blocks in parallel on 64-bit architectures.

CBC encryption will not see a parallelization speedup since each block has a data dependency on the previous block. CBC decryption, however, is parallelizable.

GCM is fully parallelizable for both encryption and decryption.

If you’d like to submit a docs PR with your suggestions, that’d be great.

**Comment by KaneGreen** [comment]
Docs PR is ready.

-----
But I can't see the "roughly 8X speedup" you said.

AES-NI enabled: 5%~10% speedup
`RUSTFLAGS="-C target-feature=+aes,+ssse3"`
```
test aes128_decrypt_block  ... bench:       1,737 ns/iter (+/- 14) = 9432 MB/s
test aes128_decrypt_blocks ... bench:       1,629 ns/iter (+/- 13) = 10057 MB/s
test aes128_encrypt_block  ... bench:       1,736 ns/iter (+/- 10) = 9437 MB/s
test aes128_encrypt_blocks ... bench:       1,628 ns/iter (+/- 17) = 10063 MB/s
test aes128_new            ... bench:          18 ns/iter (+/- 0)
test aes192_decrypt_block  ... bench:       2,228 ns/iter (+/- 25) = 7353 MB/s
test aes192_decrypt_blocks ... bench:       2,122 ns/iter (+/- 26) = 7721 MB/s
test aes192_encrypt_block  ... bench:       2,236 ns/iter (+/- 66) = 7327 MB/s
test aes192_encrypt_blocks ... bench:       2,124 ns/iter (+/- 19) = 7713 MB/s
test aes192_new            ... bench:          20 ns/iter (+/- 0)
test aes256_decrypt_block  ... bench:       2,881 ns/iter (+/- 6) = 5686 MB/s
test aes256_decrypt_blocks ... bench:       2,588 ns/iter (+/- 60) = 6330 MB/s
test aes256_encrypt_block  ... bench:       2,889 ns/iter (+/- 22) = 5671 MB/s
test aes256_encrypt_blocks ... bench:       2,602 ns/iter (+/- 22) = 6296 MB/s
test aes256_new            ... bench:          25 ns/iter (+/- 0)
```
AES-NI disabled: 4X speedup
`RUSTFLAGS="--cfg aes_force_soft -C target-feature=+aes,+ssse3"`
```
test aes128_decrypt_block  ... bench:     307,487 ns/iter (+/- 24,924) = 53 MB/s
test aes128_decrypt_blocks ... bench:      78,218 ns/iter (+/- 857) = 209 MB/s
test aes128_encrypt_block  ... bench:     286,773 ns/iter (+/- 7,104) = 57 MB/s
test aes128_encrypt_blocks ... bench:      73,349 ns/iter (+/- 819) = 223 MB/s
test aes128_new            ... bench:         375 ns/iter (+/- 5)
test aes192_decrypt_block  ... bench:     365,500 ns/iter (+/- 8,846) = 44 MB/s
test aes192_decrypt_blocks ... bench:      92,956 ns/iter (+/- 1,523) = 176 MB/s
test aes192_encrypt_block  ... bench:     332,765 ns/iter (+/- 11,586) = 49 MB/s
test aes192_encrypt_blocks ... bench:      84,281 ns/iter (+/- 860) = 194 MB/s
test aes192_new            ... bench:         291 ns/iter (+/- 5)
test aes256_decrypt_block  ... bench:     414,590 ns/iter (+/- 3,376) = 39 MB/s
test aes256_decrypt_blocks ... bench:     105,221 ns/iter (+/- 731) = 155 MB/s
test aes256_encrypt_block  ... bench:     379,321 ns/iter (+/- 5,448) = 43 MB/s
test aes256_encrypt_blocks ... bench:      95,515 ns/iter (+/- 1,074) = 171 MB/s
test aes256_new            ... bench:         479 ns/iter (+/- 7)
```

**Comment by peterdettman** [comment]
> But I can't see the "roughly 8X speedup" you said.

My impression is that the benchmarks don't have a data dependency between successive blocks. So the compiler can inline the single-block operation, unroll the loop, and discover the ILP itself.
