### ISSUE TITLE
Performance of key initialization?

### ISSUE THREAD

**Issue by oilel** [RustCrypto/block-ciphers#357]
To initialize the key, the document says:
```
let cipher = Aes128::new(&key);
```
Someone may use Aes256::new() instead. How about the performance of initialization stage?

**Comment by tarcieri** [comment]
Initialization performs key expansion, in which the initial key is transformed into a set of round keys, the number of which will depend on the size of the original key. AES-256 uses 14 rounds, for example.

This setup definitely has nonzero cost, and ideally you can cache the expanded key if you intend to frequently reuse it.

However, the cost is typically on the order of nanoseconds, and can be hardware accelerated where available.

If you are truly concerned about performance I would suggest benchmarking for your own application.
