### ISSUE TITLE
RSA implementation

### ISSUE THREAD

**Issue by dignifiedquire** [RustCrypto/block-ciphers#37]
Disclaimer: I know this is the wrong repo, but I didn't find a good one to post this on the RustCrypto org.

I have an RSA implementation in pure rust under https://github.com/dignifiedquire/rust-rsa which I would like to publish to crates.io. But when doing so I found out that the [`rsa`](https://crates.io/crates/rsa) crate name is reserved with an empty crate by RustCrypto. I would be happy to move it into this org, and continue my work on it here, but it would be great if I could use that crate name. Thank you.

cc @newpavlov

**Comment by newpavlov** [comment]
Hi and sorry for the late reply!

I will be happy to accept this crate as part of RustCrypto project and provide you publishing rights to `rsa` crate! For a long time I wanted a pure Rust RSA implementation, but unfortunately didn't have enough time to start it.

I think the best approach will be if you'll transfer your repository to RustCrypto, after that I will rename it to `rsa`, create a group with publishing rights and will add you to it. For now I will send you an invite to join this organization.

**Comment by dignifiedquire** [comment]
great, I just transferred the repo

**Comment by newpavlov** [comment]
Great! I've added you to the @RustCrypto/rsa team and now you should have full access to the repo and publishing rights to `rsa` crate.
