### ISSUE TITLE
Very slow AES on Apple Silicon

### ISSUE THREAD

**Issue by nazar-pc** [RustCrypto/block-ciphers#373]
After some testing it turned out that sequential AES CBC that takes ~1s on 13900K@5.5GHz (166_000_000 iterations) takes ~60 seconds on M1 Pro.

I would have expected that higher frequency of 13900K and years of fine-tuning of AES-NI make it faster, but being 60x faster makes me wondering if hardware acceleration is used by this library on Apple Silicon at all. I saw PRs that have added ARMv8 support and that it worked on M1, but maybe there is still something Apple-specific to be done here.

**Comment by newpavlov** [comment]
Have you enabled the `aes_armv8` [configuration flag](https://docs.rs/aes/latest/aes/#configuration-flags)?

**Comment by nazar-pc** [comment]
I did not, I looked at `Cargo.toml` and didn't find any feature flags, so I assumed that is it. Why not having a normal feature flag for this?

**Comment by newpavlov** [comment]
Because features are a poor fit for the configuration flags. They change inner workings of the crate and, strictly speaking, not additive. Such flags should be only enabled by final applications, but users routinely ignore documentation warnings and enable such features in libraries.

I agree that it would nice for such flags to be represented in Cargo.toml, but certainly not in the form of features. I plan to write a relevant proposal for it one day.

**Comment by nazar-pc** [comment]
Tested with that flag and performance is within expected range. Looking forward to raising MSRV (1.61 is over one year old) so that performance is good by default.

Thank you!

**Comment by newpavlov** [comment]
Note that the relevant intrinsics (e.g. [`vaeseq_u8`](https://doc.rust-lang.org/stable/core/arch/aarch64/fn.vaeseq_u8.html)) are still unstable, so the hardware-accelerated backend for AArch64 will be behind the configuration flag for some time still.

**Comment by tarcieri** [comment]
They're stable as of Rust 1.72 I believe

**Comment by nazar-pc** [comment]
On beta already, but I guess you'll want to wait for a few releases after it is stable: https://doc.rust-lang.org/beta/core/arch/aarch64/fn.vaeseq_u8.html

**Comment by tarcieri** [comment]
In the next breaking release of `aes` we can bump MSRV to 1.72 and remove the feature gate.

That will probably be at least a few months away if not more.
