### ISSUE TITLE
aes: compilation errors on `cg_clif` due to lack of intrinsics support

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/block-ciphers#391]
See:

- https://github.com/rust-lang/rustc_codegen_cranelift/issues/1409
- https://github.com/rust-lang/rustc_codegen_cranelift/issues/1410

Cranelift doesn't support these intrinsics yet, so ~~compilation fails~~ it inserts traps instead of using the intrinsics.

I've suggested `cfg(aes_force_soft)` as a workaround, but it would be nice if this just worked, and even better if hardware acceleration worked.

One option would be to use inline assembly, which would also provide an avenue to address #385.

**Comment by tarcieri** [comment]
cc @bjorn3

**Comment by newpavlov** [comment]
It's clearly a Cranelift issue and I don't think we should do anything to address it.

**Comment by AppleSheeple** [comment]
> Cranelift doesn't support these intrinsics yet, so compilation fails.

Does compilation actually fail?

**Comment by tarcieri** [comment]
Looks like this will be addressed by https://github.com/rust-lang/rustc_codegen_cranelift/pull/1425

Going to go ahead and close this.
