### ISSUE TITLE
Is it necessary to recreate the cipher after every use?

### ISSUE THREAD

**Issue by Veykril** [RustCrypto/block-ciphers#42]
As the title says, is it necessary to always create a new instance of the cipher, let's say blowfish as in my use case whenever i wanna do padded en/decryption? I'm asking this because the block_mode trait functions almost all take self instead of a mutable or immutable reference. This seems insanely inefficient to me and not something I'd be happy with to use tbh for something like blowfish.

**Comment by newpavlov** [comment]
You can [create](https://github.com/RustCrypto/block-ciphers/blob/master/block-modes/src/cbc.rs#L33) a block mode instance from initialized block cipher, it's a very cheap operation (it just copies block cipher state and IV), which in some cases can be optimized-out by compiler, so I don't think it will be a bottleneck.

**Comment by newpavlov** [comment]
It's to protect against accidental reuse of a block mode state, i.e. after you've encrypted/decrypted a message with a given key/IV pair it usually does not make sense to continue using the resulted state. I guess we could add methods like `encrypt_and_reset(&mut self, buffer: &mut [u8], pos: usize, new_iv: Iv)`. Can you write a PR if you are interested in it?
