### ISSUE TITLE
migration guide for aes 0.7 (with ctr) to aes 0.8?

### ISSUE THREAD

**Issue by sedan-cell** [RustCrypto/block-ciphers#425]
is there migration guide? crates.io says to use aes instead but the api changed and isnt documented which broke some code of mine. is there a guide somewhere on migrating to the merged crate when aes256-ctr was used in code?

**Comment by newpavlov** [comment]
No, we do not provide any migration guides outside of changelogs. You need to check [docs](https://docs.rs/ctr/0.9.2/ctr/index.html) for the new version and migrate your code accordingly. If you have any questions, feel free to ask them in our [Zulip chat](https://rustcrypto.zulipchat.com/) or on the [URLO forum](https://users.rust-lang.org).

Note that we are in the process of preparing the next release cycle, so you may want to postpone your migration until then.
