### ISSUE TITLE
Implement std::fmt::Display, std::error::Error for errors

### ISSUE THREAD

**Issue by yerke** [RustCrypto/block-ciphers#44]
Hi. Thank you for your work on this crate.

Is it possible to implement `std::fmt::Display`, `std::error::Error` traits for errors, such as `block_modes::BlockModeError`, `block_modes::InvalidKeyIvLength`?
This way it will be straightforward for users to do `impl From<BlockModeError> for MyLocalError` as described in https://doc.rust-lang.org/stable/rust-by-example/error/multiple_error_types/wrap_error.html.

Thanks.

**Comment by yerke** [comment]
I think there is some sort of confusion here. You have linked the implementation for `InvalidKeyLength`, not `InvalidKeyIvLength` or `BlockModeError`.

**Comment by newpavlov** [comment]
Ah, you've meant errors from `block-modes` crate. I will add impls right away.

**Comment by yerke** [comment]
Thank you for such quick turnaround!
