### ISSUE TITLE
The security audit link in `README.md` needs updating.

### ISSUE THREAD

**Issue by weaversa** [RustCrypto/block-ciphers#449]
README.md currently points to: https://research.nccgroup.com/2020/02/26/public-report-rustcrypto-aes-gcm-and-chacha20poly1305-implementation-review/

This link provides a 404 error and needs to be updated.

**Comment by tarcieri** [comment]
It appears to have moved to: https://www.nccgroup.com/us/research-blog/public-report-rustcrypto-aesgcm-and-chacha20pluspoly1305-implementation-review/

**Comment by tarcieri** [comment]
The PDF is on archive.org, at least: https://research.nccgroup.com/wp-content/uploads/2020/02/NCC_Group_MobileCoin_RustCrypto_AESGCM_ChaCha20Poly1305_Implementation_Review_2020-02-12_v1.0.pdf

**Comment by tarcieri** [comment]
The PDF is on archive.org, at least: https://web.archive.org/web/20240108154854/https://research.nccgroup.com/wp-content/uploads/2020/02/NCC_Group_MobileCoin_RustCrypto_AESGCM_ChaCha20Poly1305_Implementation_Review_2020-02-12_v1.0.pdf
