### ISSUE TITLE
Use travis-ci, to check if PR-Code has been formatted with rustfmt

### ISSUE THREAD

**Issue by Luro02** [RustCrypto/block-ciphers#54]
https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

**Comment by newpavlov** [comment]
In some repositories we already do that. I guess we in future should more or less unify CI config.

**Comment by clintnetwork** [comment]
Github action is very cool :p

PS: @newpavlov I've emailed you, I hope you could answer me :>

**Comment by Luro02** [comment]
@clintnetwork yeah, but the config files are a pain to setup. (like different platforms, other compiler, cache...)

**Comment by newpavlov** [comment]
We now check formatting (and clippy) as part of GitHub Action jobs.
