### ISSUE TITLE
Develop trait for tweakable block ciphers

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/block-ciphers#6]
Recently added Threefish is a [tweakable](http://people.csail.mit.edu/rivest/LiskovRivest-TweakableBlockCiphers.pdf) block cipher, thus we need an appropriate trait for it.

Currently I am thinking of using this:
```Rust
pub trait TweakableBlockCipher {
    type BlockSize: ArrayLength<u8>;
    type TweakSize: ArrayLength<u8>;

    fn encrypt(&self, block: &mut Block<Self::BlockSize>,  tweak: &Block<Self::TweakSize>);

    fn decrypt(&self, block: &mut Block<Self::BlockSize>, tweak: &Block<Self::TweakSize>);
}
```

In addition to it I think tweakable ciphers should auto implement `BlockCipher` using zero tweak.

**Comment by eternaleye** [comment]
One thing worth noting is that tweak changes aren't necessarily free (some constructions even use tweak-dependent keys for the underlying block cipher), and an interface that can amortize this may be beneficial.

**Comment by james-darkfox** [comment]
For HCTR the TBC trait would need to recognize Variable Input Lengths and variable tweaks (depending on the AXU it is instantiated with).

I don't think `GenericArray` can currently capture variable lengths.

**Comment by newpavlov** [comment]
I will close it in favor of RustCrypto/traits#177.
