### ISSUE TITLE
std::io wrappers in the block_modes crate

### ISSUE THREAD

**Issue by fstirlitz** [RustCrypto/block-ciphers#62]
Currently, block cipher mode types in the `block_modes` crate only provide methods that operate on slices. Those are good enough when you have the entire ciphertext in memory, but in some circumstances you cannot afford that. Right now I'm trying to decrypt a file about 10 GiB in size (and it may grow larger). Loading it into RAM is kind of out of the question (given that I'm developing on a 32-bit machine, it wouldn't even fit into the address space). So an alternative interface would be nice.

One such interface would be to provide types that implement `std::io::Read` / `std::io::Write`, encrypt/decrypt it and pass along to another stream implementing the same trait. This would also make the crate easily composable with crates providing the same kind of interface, like `flate2`. (In fact, the very next thing I'd want to do would be use `flate2` to decompress what I just decrypted; with such wrapper types, it would be two lines of code.)

**Comment by tarcieri** [comment]
In general you probably shouldn't be encrypting 10GB of data with an unauthenticated block cipher which doesn't guarantee ciphertext integrity.

I'd suggest using one of the [AEAD modes](https://github.com/rustcrypto/aeads) in conjunction with a segmented AEAD construction like [CHAIN](https://github.com/miscreant/meta/issues/33) or [STREAM](https://github.com/miscreant/meta/wiki/STREAM). Unfortunately we don't provide standard implementations of these, though there is an [implementation of STREAM available in Miscreant](https://docs.rs/miscreant/latest/miscreant/stream/index.html).

That said, CHAIN/STREAM don't map nicely to an API like `std::io`, since the user must signal that a given AEAD message is the last. A simpler solution is to otherwise disallow empty AEAD messages except as an end-of-stream marker.

**Comment by fstirlitz** [comment]
Tell that to Google; I wasn't the one who was doing the encrypting. The file I am interested in is an Android backup file (as generated by `adb backup`); the format is basically a tarball compressed with zlib and optionally encrypted with AES-256 in CBC mode, with some headers. And the particular file I've got is indeed encrypted.

So thanks for the advice, but it's not really applicable to my situation.

**Comment by tarcieri** [comment]
I believe in that case you should be able to feed to be encrypted/decrypted a chunk-at-a-time to [block_modes::Cbc](https://docs.rs/block-modes/0.3.3/block_modes/struct.Cbc.html) via the [block_modes::BlockMode](https://docs.rs/block-modes/0.3.3/block_modes/trait.BlockMode.html) trait, as opposed to loading all of the data into memory.

**Comment by TjeuKayim** [comment]
I ended up with something like this:
```rust
struct AesDecoder<T: BlockMode<C, P>, C: BlockCipher, P: Padding, R> {
    cipher: T,
    reader: R,
    phantom: PhantomData<*const (C, P)>,
}

impl <T: BlockMode<C, P>, C: BlockCipher, P: Padding, R> AesDecoder<T, C, P, R> {
    fn new(cipher: T, reader: R) -> Self {
        AesDecoder { cipher, reader, phantom: PhantomData }
    }
}

impl <T: BlockMode<C, P>, C: BlockCipher, P: Padding, R: Read> Read for AesDecoder<T, C, P, R> {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let len = <C::BlockSize as Unsigned>::to_usize();
        if buf.len() < len {
            io::Error::new(io::ErrorKind::InvalidInput, "buf.len() < 128");
        }
        let buf = &mut buf[..len];
        self.reader.read(buf)?;
        self.cipher.decrypt_blocks(&mut[generic_array::GenericArray::clone_from_slice(buf)]);
        Ok(len)
    }
}
```

**Comment by fstirlitz** [comment]
That should have used `read_exact`. Otherwise you might be decrypting (at least conceptually) uninitialised memory.

**Comment by newpavlov** [comment]
I think we can close this issue as wontfix. Block modes support online processing of messages divided into blocks, so it's possible implement the desired functionality with a bit of effort. Also `block_modes` itself will be split into per-mode crates and the `BlockMode` trait will be deprecated in favor of traits from the `cipher` crate, which probably should not contain such wrappers.

**Comment by tarcieri** [comment]
An interesting place where a similar feature could be contributed is the `aead::stream` API:

https://docs.rs/aead/0.4.2/aead/stream/index.html
