### ISSUE TITLE
Updating Crate in crates.io

### ISSUE THREAD

**Issue by Slals** [RustCrypto/block-ciphers#64]
Hi,

I have push months ago the crate `serpent` but as you can see here https://crates.io/crates/serpent the version is still `0.0.0`. Is a new `cargo publish` required?

**Comment by tarcieri** [comment]
@Slals yep. Right now @newpavlov is the only one with access (and I recently asked him for access to publish it)

**Comment by Slals** [comment]
Great, I wasn't sure, thanks :) Hope your doing well guys.
