### ISSUE TITLE
AES CTS Mode

### ISSUE THREAD

**Issue by sharksforarms** [RustCrypto/block-ciphers#66]
Any plans for implementing CTS mode? https://en.wikipedia.org/wiki/Ciphertext_stealing

**Comment by tarcieri** [comment]
Not to my knowledge. It should probably be implemented generically in the [`block-modes`](https://github.com/RustCrypto/block-ciphers/tree/master/block-modes/) generically like the other block cipher modes of operation.

**Comment by newpavlov** [comment]
Closing it in favor of RustCrypto/block-modes#1
